name = "GhpGhxRegistry"
uuid = "c9f183cb-7636-4d3d-8134-7493cd11ce75"
repo = "https://github.com/bill-becker/GhpGhxRegistry.jl.git"
description = "This is only a test."

[packages]
28cd688e-7cf2-11e8-01a0-0dc1d6450aeb = { name = "TestPackage", path = "TestPackage" }